create table if not exists public.verified_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_by_email text,
  created_at timestamptz not null default now()
);

insert into public.verified_users (email, created_by_email)
values
  ('erick.grau@chibitek.com', 'system'),
  ('puhalenthirv@gmail.com', 'system'),
  ('evanchin0322@gmail.com', 'system')
on conflict (email) do nothing;
