-- Promote verified_users to admins model.
-- If verified_users exists, rename it; otherwise create admins directly.

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public' and table_name = 'verified_users'
  ) then
    if not exists (
      select 1
      from information_schema.tables
      where table_schema = 'public' and table_name = 'admins'
    ) then
      alter table public.verified_users rename to admins;
    else
      insert into public.admins (email, created_by_email, created_at)
      select v.email, v.created_by_email, coalesce(v.created_at, now())
      from public.verified_users v
      on conflict (email) do nothing;
    end if;
  end if;
end $$;

create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_by_email text,
  created_at timestamptz not null default now()
);

create index if not exists admins_created_at_idx
  on public.admins (created_at desc);

insert into public.admins (email, created_by_email)
values
  ('erick.grau@chibitek.com', 'system'),
  ('puhalenthirv@gmail.com', 'system'),
  ('evanchin0322@gmail.com', 'system')
on conflict (email) do nothing;
